import os

# Paths
ROOT_PATH = os.path.abspath('.')
IMAGE_PATH = os.path.join(
    ROOT_PATH, 'Files', 'icon.png'
)

# Colors
PRIMARY_COLOR = '1e81b0'
DARKER_PRIMARY_COLOR = '16658a'
DARKEST_PRIMARY_COLOR = '115270'

#sizing 
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 29
SMALL_FONT_SIZE = 18
DEFAULT_MARGIN = 15
MINIMUM_WIDTH = 500